# Generated by Django 5.2.8 on 2025-11-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('emocion', models.CharField(choices=[('feliz', 'Feliz'), ('contento', 'Contento'), ('neutral', 'Neutral'), ('triste', 'Triste'), ('ansioso', 'Ansioso'), ('enojado', 'Enojado')], max_length=20)),
                ('nivel_intensidad', models.IntegerField(default=5)),
                ('nivel_energia', models.IntegerField(default=5)),
                ('nota', models.TextField(blank=True, null=True)),
                ('actividades', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
