# Generated by Django 5.2.8 on 2025-11-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('notificaciones_diarias', models.BooleanField(default=True)),
                ('notificaciones_misiones', models.BooleanField(default=True)),
                ('tema_oscuro', models.BooleanField(default=False)),
                ('nivel_actual', models.IntegerField(default=1)),
                ('experiencia_actual', models.IntegerField(default=0)),
                ('es_premium', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
